# --- Chiavi Globali (per sicurezza) ---
region = "sfo3"
endpoint = "https://sfo3.digitaloceanspaces.com"
bucket_name = "ihosp-kross-archive"
access_key = "DO801NR7AVQC4RBXZRUZ"
secret_key = "Vm1MTotXbUaTMGPAy0Y2Y8hweYDpqzYrr4sx41DbEEg"

# --- Chiavi nel Gruppo DigitalOcean ---
[digitalocean]
region = "sfo3"
endpoint = "https://sfo3.digitaloceanspaces.com"
bucket_name = "ihosp-kross-archive"
access_key = "DO801NR7AVQC4RBXZRUZ"
secret_key = "Vm1MTotXbUaTMGPAy0Y2Y8hweYDpqzYrr4sx41DbEEg"