# --- LINK GOOGLE DRIVE (In alto per sicurezza) ---
URL_EVENTI = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS5PFsxKhuuQxR2BZCKqy2DAtoxOJjytS1ZKvUjnfdI4cMql_wBR9fMqEQTlHeEIE7MDdGD3zsL1_I8/pub?gid=0&single=true&output=csv"

# --- CHIAVI GLOBALI ---
region = "sfo3"
endpoint = "https://sfo3.digitaloceanspaces.com"
bucket_name = "ihosp-kross-archive"
access_key = "DO801NR7AVQC4RBXZRUZ"
secret_key = "Vm1MTotXbUaTMGPAy0Y2Y8hweYDpqzYrr4sx41DbEEg"

# --- GRUPPO DIGITALOCEAN ---
[digitalocean]
region = "sfo3"
endpoint = "https://sfo3.digitaloceanspaces.com"
bucket_name = "ihosp-kross-archive"
access_key = "DO801NR7AVQC4RBXZRUZ"
secret_key = "Vm1MTotXbUaTMGPAy0Y2Y8hweYDpqzYrr4sx41DbEEg"